/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-alu-sr-cli-3.4.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.alusr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-alu-sr-cli-3.4.yang */
public class tailfAluSrId extends ConfNamespace {
    public static final int hash = 820686121;
    public int hash() {
        return tailfAluSrId.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/alu-sr-cli-3.4";
    public String id() {
        return tailfAluSrId.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/alu-sr-cli-3.4";
    public String uri() {
        return tailfAluSrId.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfAluSrId.uri);
    }

    public static final String prefix = "alu-sr-cli-3.4";
    public String prefix() {
        return tailfAluSrId.prefix;
    }

    public tailfAluSrId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _alu_sr_cli_30x2e4 = 332324600;
    public static final String _alu_sr_cli_30x2e4_ = "alu-sr-cli-3.4";
}
