/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-scheduler.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-scheduler.yang */
public class tailfNcsScheduler extends ConfNamespace {
    public static final int hash = 70931911;
    public int hash() {
        return tailfNcsScheduler.hash;
    }

    public static final String id = "_cisco-nso-nc-5.7:cisco-nso-nc-5.7#http://tail-f.com/ns/ncs-scheduler";
    public String id() {
        return tailfNcsScheduler.id;
    }

    public static final String uri = "_cisco-nso-nc-5.7:cisco-nso-nc-5.7#http://tail-f.com/ns/ncs-scheduler";
    public String uri() {
        return tailfNcsScheduler.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsScheduler.uri);
    }

    public static final String prefix = "scheduler";
    public String prefix() {
        return tailfNcsScheduler.prefix;
    }

    public tailfNcsScheduler() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _max_size = 1087447952;
    public static final String _max_size_ = "max-size";
    public static final int    _trigger = 1458637089;
    public static final String _trigger_ = "trigger";
    public static final int    _next_run_time = 1521626050;
    public static final String _next_run_time_ = "next-run-time";
    public static final int    _sequence_no = 1873596377;
    public static final String _sequence_no_ = "sequence-no";
    public static final int    _older_than = 1805080387;
    public static final String _older_than_ = "older-than";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _display = 2135153981;
    public static final String _display_ = "display";
    public static final int    _time = 190171445;
    public static final String _time_ = "time";
    public static final int    _get_next_run_times = 1498123587;
    public static final String _get_next_run_times_ = "get-next-run-times";
    public static final int    _when = 60139460;
    public static final String _when_ = "when";
    public static final int    _succeeded = 299422841;
    public static final String _succeeded_ = "succeeded";
    public static final int    _action_name = 719374744;
    public static final String _action_name_ = "action-name";
    public static final int    _action_node = 866468042;
    public static final String _action_node_ = "action-node";
    public static final int    _action_params = 1409245453;
    public static final String _action_params_ = "action-params";
    public static final int    _suspended = 279080502;
    public static final String _suspended_ = "suspended";
    public static final int    _resume = 696916453;
    public static final String _resume_ = "resume";
    public static final int    _task = 257853661;
    public static final String _task_ = "task";
    public static final int    _hours = 1625129637;
    public static final String _hours_ = "hours";
    public static final int    _purged_history_entries = 1500713055;
    public static final String _purged_history_entries_ = "purged-history-entries";
    public static final int    _history = 919502929;
    public static final String _history_ = "history";
    public static final int    _minutes = 1222309332;
    public static final String _minutes_ = "minutes";
    public static final int    _schedule = 1642863984;
    public static final String _schedule_ = "schedule";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _ha_mode = 1735430019;
    public static final String _ha_mode_ = "ha-mode";
    public static final int    _days = 723976734;
    public static final String _days_ = "days";
    public static final int    _weeks = 323453812;
    public static final String _weeks_ = "weeks";
    public static final int    _duration = 686902226;
    public static final String _duration_ = "duration";
    public static final int    _purge = 521476653;
    public static final String _purge_ = "purge";
    public static final int    _ha_node_id = 1085045240;
    public static final String _ha_node_id_ = "ha-node-id";
    public static final int    _running = 59151599;
    public static final String _running_ = "running";
    public static final int    _keep = 925671416;
    public static final String _keep_ = "keep";
    public static final int    _suspend = 818110257;
    public static final String _suspend_ = "suspend";
    public static final int    _age_spec = 1564313084;
    public static final String _age_spec_ = "age-spec";
    public static final int    _scheduler = 930765920;
    public static final String _scheduler_ = "scheduler";
    public static final int    _seconds = 1442107370;
    public static final String _seconds_ = "seconds";
    public static final int    _history_entry = 943977655;
    public static final String _history_entry_ = "history-entry";
}
