/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-kicker-extension.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-kicker-extension.yang */
public class tailfNcsKickerExtension extends ConfNamespace {
    public static final int hash = 626863229;
    public int hash() {
        return tailfNcsKickerExtension.hash;
    }

    public static final String id = "_cisco-nso-nc-5.7:cisco-nso-nc-5.7#http://tail-f.com/ns/ncs-kicker";
    public String id() {
        return tailfNcsKickerExtension.id;
    }

    public static final String uri = "_cisco-nso-nc-5.7:cisco-nso-nc-5.7#http://tail-f.com/ns/ncs-kicker";
    public String uri() {
        return tailfNcsKickerExtension.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsKickerExtension.uri);
    }

    public static final String prefix = "ncs-kicker";
    public String prefix() {
        return tailfNcsKickerExtension.prefix;
    }

    public tailfNcsKickerExtension() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _action_name = 719374744;
    public static final String _action_name_ = "action-name";
    public static final int    _kick_node = 1324530621;
    public static final String _kick_node_ = "kick-node";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _variable = 488361488;
    public static final String _variable_ = "variable";
    public static final int    _selector_expr = 764630658;
    public static final String _selector_expr_ = "selector-expr";
    public static final int    _notification_kicker = 1296828952;
    public static final String _notification_kicker_ = "notification-kicker";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
}
