/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-progress.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-progress.yang */
public class tailfProgress extends ConfNamespace {
    public static final int hash = 744611331;
    public int hash() {
        return tailfProgress.hash;
    }

    public static final String id = "_cisco-nso-nc-5.7:cisco-nso-nc-5.7#http://tail-f.com/ns/progress";
    public String id() {
        return tailfProgress.id;
    }

    public static final String uri = "_cisco-nso-nc-5.7:cisco-nso-nc-5.7#http://tail-f.com/ns/progress";
    public String uri() {
        return tailfProgress.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfProgress.uri);
    }

    public static final String prefix = "progress";
    public String prefix() {
        return tailfProgress.prefix;
    }

    public tailfProgress() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _max_size = 1087447952;
    public static final String _max_size_ = "max-size";
    public static final int    _trace_id = 1065151221;
    public static final String _trace_id_ = "trace-id";
    public static final int    _older_than = 1805080387;
    public static final String _older_than_ = "older-than";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _destination = 1426812369;
    public static final String _destination_ = "destination";
    public static final int    _purged_events = 608871404;
    public static final String _purged_events_ = "purged-events";
    public static final int    _phase = 1431747117;
    public static final String _phase_ = "phase";
    public static final int    _verbosity = 680524267;
    public static final String _verbosity_ = "verbosity";
    public static final int    _trace = 1896625767;
    public static final String _trace_ = "trace";
    public static final int    _transaction_id = 1239501533;
    public static final String _transaction_id_ = "transaction-id";
    public static final int    _timer = 337753833;
    public static final String _timer_ = "timer";
    public static final int    _event = 1332659655;
    public static final String _event_ = "event";
    public static final int    _datastore = 449538578;
    public static final String _datastore_ = "datastore";
    public static final int    _session_id = 372565948;
    public static final String _session_id_ = "session-id";
    public static final int    _annotation = 87780038;
    public static final String _annotation_ = "annotation";
    public static final int    _oper_data = 454130417;
    public static final String _oper_data_ = "oper-data";
    public static final int    _context = 1600175075;
    public static final String _context_ = "context";
    public static final int    _filter = 518848087;
    public static final String _filter_ = "filter";
    public static final int    _local_user = 1479564322;
    public static final String _local_user_ = "local-user";
    public static final int    _hours = 1625129637;
    public static final String _hours_ = "hours";
    public static final int    _progress = 1202957834;
    public static final String _progress_ = "progress";
    public static final int    _message = 1674281495;
    public static final String _message_ = "message";
    public static final int    _timestamp = 35058824;
    public static final String _timestamp_ = "timestamp";
    public static final int    _minutes = 1222309332;
    public static final String _minutes_ = "minutes";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _format = 1150348190;
    public static final String _format_ = "format";
    public static final int    _weeks = 323453812;
    public static final String _weeks_ = "weeks";
    public static final int    _days = 723976734;
    public static final String _days_ = "days";
    public static final int    _duration = 686902226;
    public static final String _duration_ = "duration";
    public static final int    _subsystem = 1972091070;
    public static final String _subsystem_ = "subsystem";
    public static final int    _file = 867066344;
    public static final String _file_ = "file";
    public static final int    _purge = 521476653;
    public static final String _purge_ = "purge";
    public static final int    _pre_commit_running = 1425038667;
    public static final String _pre_commit_running_ = "pre-commit-running";
    public static final int    _age_spec = 1564313084;
    public static final String _age_spec_ = "age-spec";
    public static final int    _seconds = 1442107370;
    public static final String _seconds_ = "seconds";
}
