#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.4.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.4.yang


class ns(object):
    hash = 690104408

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.4"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.4"

    prefix = "cisco-nso-nc-5.4"

    cisco_nso_nc_50x2e4_cisco_nso_nc_50x2e4 = 123305120
    cisco_nso_nc_50x2e4_cisco_nso_nc_50x2e4_ = "cisco-nso-nc-5.4"
