#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc.yang


class ns(object):
    hash = 808148602

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc"

    prefix = "cisco-nso-nc"

    cisco_nso_nc_cisco_nso_nc = 163646412
    cisco_nso_nc_cisco_nso_nc_ = "cisco-nso-nc"
