#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-progress.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-progress.yang


class ns(object):
    hash = 111104245

    id = "_cisco-nso-nc-5.4:cisco-nso-nc-5.4#http://tail-f.com/ns/ncs-progress"

    uri = "_cisco-nso-nc-5.4:cisco-nso-nc-5.4#http://tail-f.com/ns/ncs-progress"

    prefix = "ncs-progress"

    ncs_progress_commit = 6
    ncs_progress_commit_ = "commit"
    ncs_progress_debug = 189210324
    ncs_progress_debug_ = "debug"
    ncs_progress_all_devices = 1435007205
    ncs_progress_all_devices_ = "all-devices"
    ncs_progress_abort = 5
    ncs_progress_abort_ = "abort"
    ncs_progress_pre_lock_create = 1
    ncs_progress_pre_lock_create_ = "pre-lock-create"
    ncs_progress_subscriber = 2
    ncs_progress_subscriber_ = "subscriber"
    ncs_progress_show_offline = 14
    ncs_progress_show_offline_ = "show-offline"
    ncs_progress_uninitialize = 3
    ncs_progress_uninitialize_ = "uninitialize"
    ncs_progress_device = 617911018
    ncs_progress_device_ = "device"
    ncs_progress_all_services = 292973383
    ncs_progress_all_services_ = "all-services"
    ncs_progress_show_stats = 15
    ncs_progress_show_stats_ = "show-stats"
    ncs_progress_pre_modification = 0
    ncs_progress_pre_modification_ = "pre-modification"
    ncs_progress_noconnect = 0
    ncs_progress_noconnect_ = "noconnect"
    ncs_progress_device_phase = 921652140
    ncs_progress_device_phase_ = "device-phase"
    ncs_progress_prepare = 4
    ncs_progress_prepare_ = "prepare"
    ncs_progress_device_choice = 1217912419
    ncs_progress_device_choice_ = "device-choice"
    ncs_progress_cmd = 21
    ncs_progress_cmd_ = "cmd"
    ncs_progress_post_modification = 3
    ncs_progress_post_modification_ = "post-modification"
    ncs_progress_revert = 7
    ncs_progress_revert_ = "revert"
    ncs_progress_commit_queue_id = 1984880485
    ncs_progress_commit_queue_id_ = "commit-queue-id"
    ncs_progress_show_stats_path = 17
    ncs_progress_show_stats_path_ = "show-stats-path"
    ncs_progress_persist = 8
    ncs_progress_persist_ = "persist"
    ncs_progress_node = 2084421367
    ncs_progress_node_ = "node"
    ncs_progress_service_type = 1145594576
    ncs_progress_service_type_ = "service-type"
    ncs_progress_kicker = 1
    ncs_progress_kicker_ = "kicker"
    ncs_progress_initialize = 2
    ncs_progress_initialize_ = "initialize"
    ncs_progress_is_alive = 18
    ncs_progress_is_alive_ = "is-alive"
    ncs_progress_scp = 13
    ncs_progress_scp_ = "scp"
    ncs_progress_keep_alive = 19
    ncs_progress_keep_alive_ = "keep-alive"
    ncs_progress_xpath = 0
    ncs_progress_xpath_ = "xpath"
    ncs_progress_service = 855380710
    ncs_progress_service_ = "service"
    ncs_progress_get_trans_id = 10
    ncs_progress_get_trans_id_ = "get-trans-id"
    ncs_progress_package = 1915468916
    ncs_progress_package_ = "package"
    ncs_progress_show_partial = 12
    ncs_progress_show_partial_ = "show-partial"
    ncs_progress_connect = 1
    ncs_progress_connect_ = "connect"
    ncs_progress_close = 9
    ncs_progress_close_ = "close"
    ncs_progress_object = 885579523
    ncs_progress_object_ = "object"
    ncs_progress_show_stats_list = 16
    ncs_progress_show_stats_list_ = "show-stats-list"
    ncs_progress_create = 2
    ncs_progress_create_ = "create"
    ncs_progress_service_phase = 121995776
    ncs_progress_service_phase_ = "service-phase"
    ncs_progress_device_group = 569107274
    ncs_progress_device_group_ = "device-group"
    ncs_progress_reconnect = 20
    ncs_progress_reconnect_ = "reconnect"
    ncs_progress_show = 11
    ncs_progress_show_ = "show"
    actionpoint_servicepoints = "servicepoints"
