/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-yang-library.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-yang-library.yang */
public class ietfYangLibrary extends ConfNamespace {
    public static final int hash = 1210915617;
    public int hash() {
        return ietfYangLibrary.hash;
    }

    public static final String id = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#urn:ietf:params:xml:ns:yang:ietf-yang-library";
    public String id() {
        return ietfYangLibrary.id;
    }

    public static final String uri = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#urn:ietf:params:xml:ns:yang:ietf-yang-library";
    public String uri() {
        return ietfYangLibrary.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfYangLibrary.uri);
    }

    public static final String prefix = "yanglib";
    public String prefix() {
        return ietfYangLibrary.prefix;
    }

    public ietfYangLibrary() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _schema = 1919828639;
    public static final String _schema_ = "schema";
    public static final int    _revision = 1794066410;
    public static final String _revision_ = "revision";
    public static final int    _feature = 2072953574;
    public static final String _feature_ = "feature";
    public static final int    _yang_library_change = 385569445;
    public static final String _yang_library_change_ = "yang-library-change";
    public static final int    _deviation = 1796840446;
    public static final String _deviation_ = "deviation";
    public static final int    _modules_state = 1352300643;
    public static final String _modules_state_ = "modules-state";
    public static final int    _namespace = 1847615892;
    public static final String _namespace_ = "namespace";
    public static final int    _conformance_type = 1162662605;
    public static final String _conformance_type_ = "conformance-type";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _module_set_id = 1560116046;
    public static final String _module_set_id_ = "module-set-id";
    public static final int    _module = 241869139;
    public static final String _module_ = "module";
    public static final int    _submodule = 1477119504;
    public static final String _submodule_ = "submodule";
}
