/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nso-nc-4.7.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-4.7.yang */
public class tailfNedIdCiscoNsoNc4_7 extends ConfNamespace {
    public static final int hash = 539134429;
    public int hash() {
        return tailfNedIdCiscoNsoNc4_7.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-4.7";
    public String id() {
        return tailfNedIdCiscoNsoNc4_7.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-4.7";
    public String uri() {
        return tailfNedIdCiscoNsoNc4_7.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNsoNc4_7.uri);
    }

    public static final String prefix = "cisco-nso-nc-4.7";
    public String prefix() {
        return tailfNedIdCiscoNsoNc4_7.prefix;
    }

    public tailfNedIdCiscoNsoNc4_7() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nso_nc_40x2e7 = 1190434142;
    public static final String _cisco_nso_nc_40x2e7_ = "cisco-nso-nc-4.7";
}
