/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.ios.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-stats.yang */
public class CiscoIosStats extends ConfNamespace {
    public static final int hash = 127096768;
    public int hash() {
        return CiscoIosStats.hash;
    }

    public static final String id = "_cisco-ios-cli-3.8:cisco-ios-cli-3.8#urn:ios-stats";
    public String id() {
        return CiscoIosStats.id;
    }

    public static final String uri = "_cisco-ios-cli-3.8:cisco-ios-cli-3.8#urn:ios-stats";
    public String uri() {
        return CiscoIosStats.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIosStats.uri);
    }

    public static final String prefix = "ios-stats";
    public String prefix() {
        return CiscoIosStats.prefix;
    }

    public CiscoIosStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ping = 888696325;
    public static final String _ping_ = "ping";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _commands = 913421552;
    public static final String _commands_ = "commands";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _exec = 1716494663;
    public static final String _exec_ = "exec";
    public static final int    _time = 190171445;
    public static final String _time_ = "time";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _mac_address = 2110689796;
    public static final String _mac_address_ = "mac-address";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _rpc_idle_timeout = 224516963;
    public static final String _rpc_idle_timeout_ = "rpc-idle-timeout";
    public static final int    _ip_address = 36594129;
    public static final String _ip_address_ = "ip-address";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _traceroute = 739383050;
    public static final String _traceroute_ = "traceroute";
    public static final int    _idle_timeout = 1670649975;
    public static final String _idle_timeout_ = "idle-timeout";
    public static final int    _clear = 634788371;
    public static final String _clear_ = "clear";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _args = 578380655;
    public static final String _args_ = "args";
    public static final int    _license = 1917123854;
    public static final String _license_ = "license";
    public static final int    _reload = 1336127569;
    public static final String _reload_ = "reload";
    public static final int    _copy = 1887233912;
    public static final String _copy_ = "copy";
    public static final int    _show = 1568086057;
    public static final String _show_ = "show";
}
