#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-4.7.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-4.7.yang


class ns(object):
    hash = 539134429

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-4.7"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-4.7"

    prefix = "cisco-nso-nc-4.7"

    cisco_nso_nc_40x2e7_cisco_nso_nc_40x2e7 = 1190434142
    cisco_nso_nc_40x2e7_cisco_nso_nc_40x2e7_ = "cisco-nso-nc-4.7"
