#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-yang-library.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-yang-library.yang


class ns(object):
    hash = 1210915617

    id = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#urn:ietf:params:xml:ns:yang:ietf-yang-library"

    uri = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#urn:ietf:params:xml:ns:yang:ietf-yang-library"

    prefix = "yanglib"

    yanglib_implement = 0
    yanglib_implement_ = "implement"
    yanglib_schema = 1919828639
    yanglib_schema_ = "schema"
    yanglib_revision = 1794066410
    yanglib_revision_ = "revision"
    yanglib_feature = 2072953574
    yanglib_feature_ = "feature"
    yanglib_yang_library_change = 385569445
    yanglib_yang_library_change_ = "yang-library-change"
    yanglib_deviation = 1796840446
    yanglib_deviation_ = "deviation"
    yanglib_modules_state = 1352300643
    yanglib_modules_state_ = "modules-state"
    yanglib_namespace = 1847615892
    yanglib_namespace_ = "namespace"
    yanglib_conformance_type = 1162662605
    yanglib_conformance_type_ = "conformance-type"
    yanglib_name = 1998270519
    yanglib_name_ = "name"
    yanglib_module_set_id = 1560116046
    yanglib_module_set_id_ = "module-set-id"
    yanglib_import = 1
    yanglib_import_ = "import"
    yanglib_module = 241869139
    yanglib_module_ = "module"
    yanglib_submodule = 1477119504
    yanglib_submodule_ = "submodule"
