#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-scheduler.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-scheduler.yang


class ns(object):
    hash = 556264824

    id = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#http://tail-f.com/ns/ncs-scheduler"

    uri = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#http://tail-f.com/ns/ncs-scheduler"

    prefix = "scheduler"

    scheduler_info = 2062105651
    scheduler_info_ = "info"
    scheduler_trigger = 1458637089
    scheduler_trigger_ = "trigger"
    scheduler_next_run_time = 1521626050
    scheduler_next_run_time_ = "next-run-time"
    scheduler_sequence_no = 1873596377
    scheduler_sequence_no_ = "sequence-no"
    scheduler_enabled = 197426095
    scheduler_enabled_ = "enabled"
    scheduler_result = 401396173
    scheduler_result_ = "result"
    scheduler_display = 2135153981
    scheduler_display_ = "display"
    scheduler_time = 190171445
    scheduler_time_ = "time"
    scheduler_slave = 1
    scheduler_slave_ = "slave"
    scheduler_get_next_run_times = 1498123587
    scheduler_get_next_run_times_ = "get-next-run-times"
    scheduler_when = 60139460
    scheduler_when_ = "when"
    scheduler_succeeded = 299422841
    scheduler_succeeded_ = "succeeded"
    scheduler_action_name = 719374744
    scheduler_action_name_ = "action-name"
    scheduler_action_node = 866468042
    scheduler_action_node_ = "action-node"
    scheduler_action_params = 1409245453
    scheduler_action_params_ = "action-params"
    scheduler_master = 0
    scheduler_master_ = "master"
    scheduler_suspended = 279080502
    scheduler_suspended_ = "suspended"
    scheduler_resume = 696916453
    scheduler_resume_ = "resume"
    scheduler_task = 257853661
    scheduler_task_ = "task"
    scheduler_history = 919502929
    scheduler_history_ = "history"
    scheduler_schedule = 1642863984
    scheduler_schedule_ = "schedule"
    scheduler_name = 1998270519
    scheduler_name_ = "name"
    scheduler_ha_mode = 1735430019
    scheduler_ha_mode_ = "ha-mode"
    scheduler_duration = 686902226
    scheduler_duration_ = "duration"
    scheduler_ha_node_id = 1085045240
    scheduler_ha_node_id_ = "ha-node-id"
    scheduler_is_running = 1941256924
    scheduler_is_running_ = "is-running"
    scheduler_keep = 925671416
    scheduler_keep_ = "keep"
    scheduler_suspend = 818110257
    scheduler_suspend_ = "suspend"
    scheduler_scheduler = 930765920
    scheduler_scheduler_ = "scheduler"
