#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-ned.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-ned.yang


class ns(object):
    hash = 1395959697

    id = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#http://tail-f.com/ns/ncs-ned"

    uri = "_cisco-nso-nc-4.7:cisco-nso-nc-4.7#http://tail-f.com/ns/ncs-ned"

    prefix = "ned"

    ned_netconf_ned_id = 973516117
    ned_netconf_ned_id_ = "netconf-ned-id"
    ned_cli_ned_id = 868449949
    ned_cli_ned_id_ = "cli-ned-id"
    ned_netconf = 1625535416
    ned_netconf_ = "netconf"
    ned_generic_ned_id = 878713830
    ned_generic_ned_id_ = "generic-ned-id"
    ned_lsa_netconf = 1104954683
    ned_lsa_netconf_ = "lsa-netconf"
