/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-dell-ftos-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.force10.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-dell-ftos-stats.yang */
public class Force10Stats extends ConfNamespace {
    public static final int hash = 29109488;
    public int hash() {
        return Force10Stats.hash;
    }

    public static final String id = "_dell-ftos-cli-3.0:dell-ftos-cli-3.0#http://tail-f.com/ned/dell-ftos-stats";
    public String id() {
        return Force10Stats.id;
    }

    public static final String uri = "_dell-ftos-cli-3.0:dell-ftos-cli-3.0#http://tail-f.com/ned/dell-ftos-stats";
    public String uri() {
        return Force10Stats.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(Force10Stats.uri);
    }

    public static final String prefix = "force10-stats";
    public String prefix() {
        return Force10Stats.prefix;
    }

    public Force10Stats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _queue_strategy = 919088899;
    public static final String _queue_strategy_ = "queue-strategy";
    public static final int    _vlan_id = 1443431623;
    public static final String _vlan_id_ = "vlan-id";
    public static final int    _underruns = 1167381215;
    public static final String _underruns_ = "underruns";
    public static final int    _percent_line_rate = 1619210305;
    public static final String _percent_line_rate_ = "percent-line-rate";
    public static final int    _packets = 384560432;
    public static final String _packets_ = "packets";
    public static final int    _pkts_over_127_byte = 354383835;
    public static final String _pkts_over_127_byte_ = "pkts-over-127-byte";
    public static final int    _pkts_over_255_byte = 1831081435;
    public static final String _pkts_over_255_byte_ = "pkts-over-255-byte";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _hw_address = 2057586783;
    public static final String _hw_address_ = "hw-address";
    public static final int    _input = 1427240772;
    public static final String _input_ = "input";
    public static final int    _last_clearing_counter = 2004021148;
    public static final String _last_clearing_counter_ = "last-clearing-counter";
    public static final int    _mac = 474706838;
    public static final String _mac_ = "mac";
    public static final int    _internet_address = 1118890225;
    public static final String _internet_address_ = "internet-address";
    public static final int    _line_mode = 1820234092;
    public static final String _line_mode_ = "line-mode";
    public static final int    _pkts_over_511_byte = 542466306;
    public static final String _pkts_over_511_byte_ = "pkts-over-511-byte";
    public static final int    _discarded = 1973722861;
    public static final String _discarded_ = "discarded";
    public static final int    _time_since_last_status_change = 1043251045;
    public static final String _time_since_last_status_change_ = "time-since-last-status-change";
    public static final int    _flowcontrol_tx = 440268204;
    public static final String _flowcontrol_tx_ = "flowcontrol-tx";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _wreddrops = 623196140;
    public static final String _wreddrops_ = "wreddrops";
    public static final int    _line_speed = 117847933;
    public static final String _line_speed_ = "line-speed";
    public static final int    _runts = 1233238779;
    public static final String _runts_ = "runts";
    public static final int    _rate_info = 574420212;
    public static final String _rate_info_ = "rate-info";
    public static final int    _mac_address_table = 1548220928;
    public static final String _mac_address_table_ = "mac-address-table";
    public static final int    _arp_timeout = 1934421324;
    public static final String _arp_timeout_ = "arp-timeout";
    public static final int    _stats = 1979611730;
    public static final String _stats_ = "stats";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _output = 171341581;
    public static final String _output_ = "output";
    public static final int    _crc = 1279813618;
    public static final String _crc_ = "crc";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _collisions = 71575584;
    public static final String _collisions_ = "collisions";
    public static final int    _overrun = 1594891277;
    public static final String _overrun_ = "overrun";
    public static final int    _packets_p_sec = 1387428172;
    public static final String _packets_p_sec_ = "packets-p-sec";
    public static final int    _broadcasts = 1582961192;
    public static final String _broadcasts_ = "broadcasts";
    public static final int    _unicasts = 766465200;
    public static final String _unicasts_ = "unicasts";
    public static final int    _line_protocol = 928833429;
    public static final String _line_protocol_ = "line-protocol";
    public static final int    _arp_type = 463658930;
    public static final String _arp_type_ = "arp-type";
    public static final int    _bytes = 1113108825;
    public static final String _bytes_ = "bytes";
    public static final int    _giants = 818355955;
    public static final String _giants_ = "giants";
    public static final int    _flowcontrol_rx = 1280436953;
    public static final String _flowcontrol_rx_ = "flowcontrol-rx";
    public static final int    _multicasts = 776393491;
    public static final String _multicasts_ = "multicasts";
    public static final int    _mbit_p_sec = 1002389585;
    public static final String _mbit_p_sec_ = "mbit-p-sec";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _throttles = 2085366271;
    public static final String _throttles_ = "throttles";
    public static final int    _current_address = 1187780207;
    public static final String _current_address_ = "current-address";
    public static final int    _ip_mtu = 1578525503;
    public static final String _ip_mtu_ = "ip-mtu";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _pkts_over_64_byte = 130104213;
    public static final String _pkts_over_64_byte_ = "pkts-over-64-byte";
    public static final int    _pkts_64_byte = 834540156;
    public static final String _pkts_64_byte_ = "pkts-64-byte";
    public static final int    _pkts_over_1023_byte = 1834212785;
    public static final String _pkts_over_1023_byte_ = "pkts-over-1023-byte";
}
