/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/ietf-ip.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.asa.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-ip.yang */
public class ietfIp extends ConfNamespace {
    public static final int hash = 88733550;
    public int hash() {
        return ietfIp.hash;
    }

    public static final String id = "_cisco-asa-cli-6.6:cisco-asa-cli-6.6#urn:ietf:params:xml:ns:yang:ietf-ip";
    public String id() {
        return ietfIp.id;
    }

    public static final String uri = "_cisco-asa-cli-6.6:cisco-asa-cli-6.6#urn:ietf:params:xml:ns:yang:ietf-ip";
    public String uri() {
        return ietfIp.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfIp.uri);
    }

    public static final String prefix = "ip";
    public String prefix() {
        return ietfIp.prefix;
    }

    public ietfIp() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _forwarding = 1238173057;
    public static final String _forwarding_ = "forwarding";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _origin = 2002579816;
    public static final String _origin_ = "origin";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _is_router = 1891156201;
    public static final String _is_router_ = "is-router";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _link_layer_address = 2084100809;
    public static final String _link_layer_address_ = "link-layer-address";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
    public static final int    _netmask = 240292132;
    public static final String _netmask_ = "netmask";
}
