/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-netconf-acm.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-netconf-acm.yang */
public class ietfNetconfAcm extends ConfNamespace {
    public static final int hash = 1289456206;
    public int hash() {
        return ietfNetconfAcm.hash;
    }

    public static final String id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#urn:ietf:params:xml:ns:yang:ietf-netconf-acm";
    public String id() {
        return ietfNetconfAcm.id;
    }

    public static final String uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#urn:ietf:params:xml:ns:yang:ietf-netconf-acm";
    public String uri() {
        return ietfNetconfAcm.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfNetconfAcm.uri);
    }

    public static final String prefix = "nacm";
    public String prefix() {
        return ietfNetconfAcm.prefix;
    }

    public ietfNetconfAcm() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    __bm_live_ncs_access_operations_type_update = 4;
    public static final String __bm_live_ncs_access_operations_type_update_ = "update";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _access_operations = 1622834780;
    public static final String _access_operations_ = "access-operations";
    public static final int    _rule = 661146188;
    public static final String _rule_ = "rule";
    public static final int    __bm_live_ncs_access_operations_type_read = 2;
    public static final String __bm_live_ncs_access_operations_type_read_ = "read";
    public static final int    __bm_ncs_rpc_notif_access_operations_type_create = 1;
    public static final String __bm_ncs_rpc_notif_access_operations_type_create_ = "create";
    public static final int    _read_default = 1809256375;
    public static final String _read_default_ = "read-default";
    public static final int    __bm_live_ncs_access_operations_type_delete = 8;
    public static final String __bm_live_ncs_access_operations_type_delete_ = "delete";
    public static final int    _protocol_operation = 1730844454;
    public static final String _protocol_operation_ = "protocol-operation";
    public static final int    _module_name = 1521916861;
    public static final String _module_name_ = "module-name";
    public static final int    _enable_external_groups = 681474854;
    public static final String _enable_external_groups_ = "enable-external-groups";
    public static final int    __bm_access_operations_type_read = 2;
    public static final String __bm_access_operations_type_read_ = "read";
    public static final int    _denied_notifications = 1423413556;
    public static final String _denied_notifications_ = "denied-notifications";
    public static final int    __bm_ncs_rpc_notif_access_operations_type_exec = 16;
    public static final String __bm_ncs_rpc_notif_access_operations_type_exec_ = "exec";
    public static final int    __bm_live_ncs_access_operations_type_create = 1;
    public static final String __bm_live_ncs_access_operations_type_create_ = "create";
    public static final int    __bm_access_operations_type_update = 4;
    public static final String __bm_access_operations_type_update_ = "update";
    public static final int    _nacm = 882296017;
    public static final String _nacm_ = "nacm";
    public static final int    _groups = 575296803;
    public static final String _groups_ = "groups";
    public static final int    __bm_ncs_rpc_notif_access_operations_type_read = 2;
    public static final String __bm_ncs_rpc_notif_access_operations_type_read_ = "read";
    public static final int    _notification = 232240424;
    public static final String _notification_ = "notification";
    public static final int    __bm_live_ncs_access_operations_type_exec = 16;
    public static final String __bm_live_ncs_access_operations_type_exec_ = "exec";
    public static final int    _data_node = 1323346008;
    public static final String _data_node_ = "data-node";
    public static final int    _group = 1540685982;
    public static final String _group_ = "group";
    public static final int    _write_default = 342649280;
    public static final String _write_default_ = "write-default";
    public static final int    __bm_ncs_rpc_notif_access_operations_type_delete = 8;
    public static final String __bm_ncs_rpc_notif_access_operations_type_delete_ = "delete";
    public static final int    __bm_access_operations_type_exec = 16;
    public static final String __bm_access_operations_type_exec_ = "exec";
    public static final int    _exec_default = 1365079393;
    public static final String _exec_default_ = "exec-default";
    public static final int    _notification_name = 1826218130;
    public static final String _notification_name_ = "notification-name";
    public static final int    __bm_access_operations_type_create = 1;
    public static final String __bm_access_operations_type_create_ = "create";
    public static final int    _denied_data_writes = 1067903842;
    public static final String _denied_data_writes_ = "denied-data-writes";
    public static final int    _denied_operations = 1711027331;
    public static final String _denied_operations_ = "denied-operations";
    public static final int    _rule_list = 755335822;
    public static final String _rule_list_ = "rule-list";
    public static final int    _user_name = 1672949661;
    public static final String _user_name_ = "user-name";
    public static final int    _comment = 452863039;
    public static final String _comment_ = "comment";
    public static final int    __bm_ncs_rpc_notif_access_operations_type_update = 4;
    public static final String __bm_ncs_rpc_notif_access_operations_type_update_ = "update";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _rule_type = 508857660;
    public static final String _rule_type_ = "rule-type";
    public static final int    __bm_access_operations_type_delete = 8;
    public static final String __bm_access_operations_type_delete_ = "delete";
    public static final int    _enable_nacm = 947489807;
    public static final String _enable_nacm_ = "enable-nacm";
    public static final int    _rpc_name = 37201271;
    public static final String _rpc_name_ = "rpc-name";
    public static final int    _action = 571883887;
    public static final String _action_ = "action";
}
