/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-acm.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-acm.yang */
public class tailfNcsAcm extends ConfNamespace {
    public static final int hash = 1853056478;
    public int hash() {
        return tailfNcsAcm.hash;
    }

    public static final String id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/yang/ncs-acm";
    public String id() {
        return tailfNcsAcm.id;
    }

    public static final String uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/yang/ncs-acm";
    public String uri() {
        return tailfNcsAcm.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsAcm.uri);
    }

    public static final String prefix = "tnacm";
    public String prefix() {
        return tailfNcsAcm.prefix;
    }

    public tailfNcsAcm() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _enforce_nacm_on_services = 646091520;
    public static final String _enforce_nacm_on_services_ = "enforce-nacm-on-services";
}
