/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-ned.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-ned.yang */
public class tailfNcsNed extends ConfNamespace {
    public static final int hash = 70095624;
    public int hash() {
        return tailfNcsNed.hash;
    }

    public static final String id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/ncs-ned";
    public String id() {
        return tailfNcsNed.id;
    }

    public static final String uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/ncs-ned";
    public String uri() {
        return tailfNcsNed.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsNed.uri);
    }

    public static final String prefix = "ned";
    public String prefix() {
        return tailfNcsNed.prefix;
    }

    public tailfNcsNed() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _netconf_ned_id = 973516117;
    public static final String _netconf_ned_id_ = "netconf-ned-id";
    public static final int    _rfc5277_id = 37234262;
    public static final String _rfc5277_id_ = "rfc5277-id";
    public static final int    _cli_ned_id = 868449949;
    public static final String _cli_ned_id_ = "cli-ned-id";
    public static final int    _snmp = 1480446066;
    public static final String _snmp_ = "snmp";
    public static final int    _netconf = 1625535416;
    public static final String _netconf_ = "netconf";
    public static final int    _ned_id = 1774190712;
    public static final String _ned_id_ = "ned-id";
    public static final int    _generic_ned_id = 878713830;
    public static final String _generic_ned_id_ = "generic-ned-id";
    public static final int    _lsa_netconf = 1104954683;
    public static final String _lsa_netconf_ = "lsa-netconf";
    public static final int    _snmp_ned_id = 1834620094;
    public static final String _snmp_ned_id_ = "snmp-ned-id";
}
