/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-netconf-ned-builder.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-netconf-ned-builder.yang */
public class tailfNcsNetconfNedBuilder extends ConfNamespace {
    public static final int hash = 723041533;
    public int hash() {
        return tailfNcsNetconfNedBuilder.hash;
    }

    public static final String id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/ncs/netconf-ned-builder";
    public String id() {
        return tailfNcsNetconfNedBuilder.id;
    }

    public static final String uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/ncs/netconf-ned-builder";
    public String uri() {
        return tailfNcsNetconfNedBuilder.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsNetconfNedBuilder.uri);
    }

    public static final String prefix = "tnnb";
    public String prefix() {
        return tailfNcsNetconfNedBuilder.prefix;
    }

    public tailfNcsNetconfNedBuilder() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _bit_dl_error = 32;
    public static final String _bit_dl_error_ = "download-error";
    public static final int    _bit_deselected = 1;
    public static final String _bit_deselected_ = "deselected";
    public static final int    _profile = 1538168517;
    public static final String _profile_ = "profile";
    public static final int    _compiler_output = 1578604919;
    public static final String _compiler_output_ = "compiler-output";
    public static final int    _location = 1827424758;
    public static final String _location_ = "location";
    public static final int    _ned_directory_path = 1576761495;
    public static final String _ned_directory_path_ = "ned-directory-path";
    public static final int    _max_download_threads = 31300361;
    public static final String _max_download_threads_ = "max-download-threads";
    public static final int    _build_ned = 36493425;
    public static final String _build_ned_ = "build-ned";
    public static final int    _build_status = 278800061;
    public static final String _build_status_ = "build-status";
    public static final int    _build_error = 1281833628;
    public static final String _build_error_ = "build-error";
    public static final int    _selected = 1500137012;
    public static final String _selected_ = "selected";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _not_found = 1919731247;
    public static final String _not_found_ = "not-found";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _bit_pending = 8;
    public static final String _bit_pending_ = "pending";
    public static final int    _save_selection = 2116845479;
    public static final String _save_selection_ = "save-selection";
    public static final int    _revision = 1794066410;
    public static final String _revision_ = "revision";
    public static final int    _select_info = 1110820427;
    public static final String _select_info_ = "select-info";
    public static final int    _no_dependencies = 390660413;
    public static final String _no_dependencies_ = "no-dependencies";
    public static final int    _build_warning = 504037989;
    public static final String _build_warning_ = "build-warning";
    public static final int    _ned_path = 1667349253;
    public static final String _ned_path_ = "ned-path";
    public static final int    _no_revisions = 805099600;
    public static final String _no_revisions_ = "no-revisions";
    public static final int    _to_directory = 134604797;
    public static final String _to_directory_ = "to-directory";
    public static final int    _feature = 2072953574;
    public static final String _feature_ = "feature";
    public static final int    _make_development_ned = 1064213877;
    public static final String _make_development_ned_ = "make-development-ned";
    public static final int    _deviation = 1796840446;
    public static final String _deviation_ = "deviation";
    public static final int    _ambiguous = 390658914;
    public static final String _ambiguous_ = "ambiguous";
    public static final int    _fetch_module_list = 26030237;
    public static final String _fetch_module_list_ = "fetch-module-list";
    public static final int    _vendor = 1639541835;
    public static final String _vendor_ = "vendor";
    public static final int    _build_error_info = 1867763619;
    public static final String _build_error_info_ = "build-error-info";
    public static final int    _bit_no_deps = 4;
    public static final String _bit_no_deps_ = "no-dependencies";
    public static final int    _local_user = 1479564322;
    public static final String _local_user_ = "local-user";
    public static final int    _in_directory = 1836397949;
    public static final String _in_directory_ = "in-directory";
    public static final int    _bit_selected = 2;
    public static final String _bit_selected_ = "selected";
    public static final int    _namespace = 1847615892;
    public static final String _namespace_ = "namespace";
    public static final int    _best_effort = 1556684121;
    public static final String _best_effort_ = "best-effort";
    public static final int    _deselect = 1534284528;
    public static final String _deselect_ = "deselect";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _select = 1473597411;
    public static final String _select_ = "select";
    public static final int    _netconf_ned_builder = 1727329174;
    public static final String _netconf_ned_builder_ = "netconf-ned-builder";
    public static final int    _project = 934555478;
    public static final String _project_ = "project";
    public static final int    _download_cache_path = 1831947648;
    public static final String _download_cache_path_ = "download-cache-path";
    public static final int    _apply = 1468797760;
    public static final String _apply_ = "apply";
    public static final int    _major_version = 423255377;
    public static final String _major_version_ = "major-version";
    public static final int    _export_ned = 226564769;
    public static final String _export_ned_ = "export-ned";
    public static final int    _import = 82100561;
    public static final String _import_ = "import";
    public static final int    _bit_downloaded = 16;
    public static final String _bit_downloaded_ = "downloaded";
    public static final int    _tar_file = 1643132563;
    public static final String _tar_file_ = "tar-file";
    public static final int    _family_name = 1394315061;
    public static final String _family_name_ = "family-name";
    public static final int    _module = 241869139;
    public static final String _module_ = "module";
    public static final int    _with_dependencies = 176147827;
    public static final String _with_dependencies_ = "with-dependencies";
    public static final int    _overwrite = 1560339033;
    public static final String _overwrite_ = "overwrite";
    public static final int    _submodule = 1477119504;
    public static final String _submodule_ = "submodule";
    public static final String actionpoint_dir_path_comp = "dir-path-comp";
}
