/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.5.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.5.yang */
public class tailfNedIdCiscoNsoNc5_5 extends ConfNamespace {
    public static final int hash = 1412712676;
    public int hash() {
        return tailfNedIdCiscoNsoNc5_5.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.5";
    public String id() {
        return tailfNedIdCiscoNsoNc5_5.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.5";
    public String uri() {
        return tailfNedIdCiscoNsoNc5_5.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNsoNc5_5.uri);
    }

    public static final String prefix = "cisco-nso-nc-5.5";
    public String prefix() {
        return tailfNedIdCiscoNsoNc5_5.prefix;
    }

    public tailfNedIdCiscoNsoNc5_5() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nso_nc_50x2e5 = 1021010265;
    public static final String _cisco_nso_nc_50x2e5_ = "cisco-nso-nc-5.5";
}
