/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nso-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc.yang */
public class tailfNedIdCiscoNsoNc extends ConfNamespace {
    public static final int hash = 808148602;
    public int hash() {
        return tailfNedIdCiscoNsoNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nso-nc";
    public String id() {
        return tailfNedIdCiscoNsoNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc";
    public String uri() {
        return tailfNedIdCiscoNsoNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNsoNc.uri);
    }

    public static final String prefix = "cisco-nso-nc";
    public String prefix() {
        return tailfNedIdCiscoNsoNc.prefix;
    }

    public tailfNedIdCiscoNsoNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nso_nc = 163646412;
    public static final String _cisco_nso_nc_ = "cisco-nso-nc";
}
