/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-monitoring.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-monitoring.yang */
public class tailfNcsMonitoring extends ConfNamespace {
    public static final int hash = 1205253828;
    public int hash() {
        return tailfNcsMonitoring.hash;
    }

    public static final String id = "_cisco-nso-nc-5.4:cisco-nso-nc-5.4#http://tail-f.com/yang/ncs-monitoring";
    public String id() {
        return tailfNcsMonitoring.id;
    }

    public static final String uri = "_cisco-nso-nc-5.4:cisco-nso-nc-5.4#http://tail-f.com/yang/ncs-monitoring";
    public String uri() {
        return tailfNcsMonitoring.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsMonitoring.uri);
    }

    public static final String prefix = "tfnm";
    public String prefix() {
        return tailfNcsMonitoring.prefix;
    }

    public tailfNcsMonitoring() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _master_node_id = 1519669186;
    public static final String _master_node_id_ = "master-node-id";
    public static final int    _netconf_container = 1625535416;
    public static final String _netconf_container_ = "netconf";
    public static final int    _read_locks = 1190580740;
    public static final String _read_locks_ = "read-locks";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _force_purge = 683976832;
    public static final String _force_purge_ = "force-purge";
    public static final int    _subscription_lock_set = 1897548819;
    public static final String _subscription_lock_set_ = "subscription-lock-set";
    public static final int    _replay_support = 1991147815;
    public static final String _replay_support_ = "replay-support";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _upper = 387913976;
    public static final String _upper_ = "upper";
    public static final int    _v3 = 1875892236;
    public static final String _v3_ = "v3";
    public static final int    _cdb = 998164659;
    public static final String _cdb_ = "cdb";
    public static final int    _ssh = 1331385911;
    public static final String _ssh_ = "ssh";
    public static final int    _prefix = 1408440115;
    public static final String _prefix_ = "prefix";
    public static final int    _range = 28853268;
    public static final String _range_ = "range";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _pending_slave = 1786241460;
    public static final String _pending_slave_ = "pending-slave";
    public static final int    _engine_id = 216790128;
    public static final String _engine_id_ = "engine-id";
    public static final int    _listen = 1581145585;
    public static final String _listen_ = "listen";
    public static final int    _smp = 2045227282;
    public static final String _smp_ = "smp";
    public static final int    _read_only_mode = 1380172856;
    public static final String _read_only_mode_ = "read-only-mode";
    public static final int    _port = 10387472;
    public static final String _port_ = "port";
    public static final int    _patches_directory = 2048197319;
    public static final String _patches_directory_ = "patches-directory";
    public static final int    _client_list = 2128680708;
    public static final String _client_list_ = "client";
    public static final int    _registration_type = 1530532966;
    public static final String _registration_type_ = "registration-type";
    public static final int    _v1 = 1223356638;
    public static final String _v1_ = "v1";
    public static final int    _exported = 1326433518;
    public static final String _exported_ = "exported";
    public static final int    _snmp_notification_subscription = 721128210;
    public static final String _snmp_notification_subscription_ = "snmp-notification-subscription";
    public static final int    _disk_size = 1172482712;
    public static final String _disk_size_ = "disk-size";
    public static final int    _mount = 454622582;
    public static final String _mount_ = "mount";
    public static final int    _compile_time = 1490339292;
    public static final String _compile_time_ = "compile-time";
    public static final int    _transaction_id = 1239501533;
    public static final String _transaction_id_ = "transaction-id";
    public static final int    _daemon_status = 215487990;
    public static final String _daemon_status_ = "daemon-status";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _waiting_for_replication_sync = 663640651;
    public static final String _waiting_for_replication_sync_ = "waiting-for-replication-sync";
    public static final int    _revision = 1794066410;
    public static final String _revision_ = "revision";
    public static final int    _tcp = 1326749881;
    public static final String _tcp_ = "tcp";
    public static final int    _pending_notification_queue = 1831795487;
    public static final String _pending_notification_queue_ = "pending-notification-queue";
    public static final int    _number_of_threads = 1675005900;
    public static final String _number_of_threads_ = "number-of-threads";
    public static final int    _pending_subscription_sync = 191180784;
    public static final String _pending_subscription_sync_ = "pending-subscription-sync";
    public static final int    _datastore = 449538578;
    public static final String _datastore_ = "datastore";
    public static final int    _notification = 232240424;
    public static final String _notification_ = "notification";
    public static final int    _typepoint = 65476354;
    public static final String _typepoint_ = "typepoint";
    public static final int    _node_id = 98319925;
    public static final String _node_id_ = "node-id";
    public static final int    _udp = 613514645;
    public static final String _udp_ = "udp";
    public static final int    _client_name = 805960493;
    public static final String _client_name_ = "client-name";
    public static final int    _load_modules = 1283158728;
    public static final String _load_modules_ = "load-modules";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _exported_to = 1583929646;
    public static final String _exported_to_ = "exported-to";
    public static final int    _ssl = 979553486;
    public static final String _ssl_ = "ssl";
    public static final int    _loaded_data_models = 21705453;
    public static final String _loaded_data_models_ = "loaded-data-models";
    public static final int    _upgrade_mode = 920147429;
    public static final String _upgrade_mode_ = "upgrade-mode";
    public static final int    _callpoints = 1592916040;
    public static final String _callpoints_ = "callpoints";
    public static final int    _ncs_state = 1920402164;
    public static final String _ncs_state_ = "ncs-state";
    public static final int    _servicepoint = 893879005;
    public static final String _servicepoint_ = "servicepoint";
    public static final int    _filename = 410894381;
    public static final String _filename_ = "filename";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _callpoint = 1469687340;
    public static final String _callpoint_ = "callpoint";
    public static final int    _default = 515137925;
    public static final String _default_ = "default";
    public static final int    _lock = 95781586;
    public static final String _lock_ = "lock";
    public static final int    _lower = 141911956;
    public static final String _lower_ = "lower";
    public static final int    _epoll = 1504875482;
    public static final String _epoll_ = "epoll";
    public static final int    _time_remaining = 196459818;
    public static final String _time_remaining_ = "time-remaining";
    public static final int    _rest_container = 98717481;
    public static final String _rest_container_ = "rest";
    public static final int    _namespace = 1847615892;
    public static final String _namespace_ = "namespace";
    public static final int    _v2c = 406691283;
    public static final String _v2c_ = "v2c";
    public static final int    _validationpoint = 761013925;
    public static final String _validationpoint_ = "validationpoint";
    public static final int    _webui_container = 1476667922;
    public static final String _webui_container_ = "webui";
    public static final int    _write_lock_set = 548245493;
    public static final String _write_lock_set_ = "write-lock-set";
    public static final int    _callbacks = 1381072421;
    public static final String _callbacks_ = "callbacks";
    public static final int    _actionpoint = 1475601241;
    public static final String _actionpoint_ = "actionpoint";
    public static final int    _snmp_inform_callback = 1298806350;
    public static final String _snmp_inform_callback_ = "snmp-inform-callback";
    public static final int    _mib = 1076211155;
    public static final String _mib_ = "mib";
    public static final int    _subscription_list = 982993959;
    public static final String _subscription_list_ = "subscription";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _patches = 851512023;
    public static final String _patches_ = "patches";
    public static final int    _cli_container = 1771971819;
    public static final String _cli_container_ = "cli";
    public static final int    _data_model = 1931346756;
    public static final String _data_model_ = "data-model";
    public static final int    _notification_stream_replay = 1106318897;
    public static final String _notification_stream_replay_ = "notification-stream-replay";
    public static final int    _file = 867066344;
    public static final String _file_ = "file";
    public static final int    _twophase = 1232700293;
    public static final String _twophase_ = "twophase";
    public static final int    _write_queue = 511743176;
    public static final String _write_queue_ = "write-queue";
    public static final int    _subscription_ids = 1787526405;
    public static final String _subscription_ids_ = "subscription-ids";
    public static final int    _mount_id = 2115124468;
    public static final String _mount_id_ = "mount-id";
    public static final int    _authorization_callbacks = 362793950;
    public static final String _authorization_callbacks_ = "authorization-callbacks";
    public static final int    _exported_to_all = 772270332;
    public static final String _exported_to_all_ = "exported-to-all";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _ha = 351929149;
    public static final String _ha_ = "ha";
    public static final int    _loaded_module = 1519580201;
    public static final String _loaded_module_ = "loaded-module";
    public static final int    _internal = 1286562807;
    public static final String _internal_ = "internal";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _authentication_callback = 1730433452;
    public static final String _authentication_callback_ = "authentication-callback";
    public static final int    _snmp_container = 1480446066;
    public static final String _snmp_container_ = "snmp";
    public static final int    _daemon = 137874048;
    public static final String _daemon_ = "daemon";
    public static final int    _ram_size = 419118552;
    public static final String _ram_size_ = "ram-size";
    public static final int    _error_formatting_callback = 1155489369;
    public static final String _error_formatting_callback_ = "error-formatting-callback";
    public static final int    _connected_slave = 55793682;
    public static final String _connected_slave_ = "connected-slave";
}
