/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-progress.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-progress.yang */
public class tailfNcsProgress extends ConfNamespace {
    public static final int hash = 111104245;
    public int hash() {
        return tailfNcsProgress.hash;
    }

    public static final String id = "_cisco-nso-nc-5.4:cisco-nso-nc-5.4#http://tail-f.com/ns/ncs-progress";
    public String id() {
        return tailfNcsProgress.id;
    }

    public static final String uri = "_cisco-nso-nc-5.4:cisco-nso-nc-5.4#http://tail-f.com/ns/ncs-progress";
    public String uri() {
        return tailfNcsProgress.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsProgress.uri);
    }

    public static final String prefix = "ncs-progress";
    public String prefix() {
        return tailfNcsProgress.prefix;
    }

    public tailfNcsProgress() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _debug = 189210324;
    public static final String _debug_ = "debug";
    public static final int    _all_devices = 1435007205;
    public static final String _all_devices_ = "all-devices";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _all_services = 292973383;
    public static final String _all_services_ = "all-services";
    public static final int    _device_phase = 921652140;
    public static final String _device_phase_ = "device-phase";
    public static final int    _device_choice = 1217912419;
    public static final String _device_choice_ = "device-choice";
    public static final int    _commit_queue_id = 1984880485;
    public static final String _commit_queue_id_ = "commit-queue-id";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _service_type = 1145594576;
    public static final String _service_type_ = "service-type";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _package = 1915468916;
    public static final String _package_ = "package";
    public static final int    _object = 885579523;
    public static final String _object_ = "object";
    public static final int    _service_phase = 121995776;
    public static final String _service_phase_ = "service-phase";
    public static final int    _device_group = 569107274;
    public static final String _device_group_ = "device-group";
    public static final String actionpoint_servicepoints = "servicepoints";
}
