/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-alarms.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-alarms.yang */
public class tailfNcsAlarms extends ConfNamespace {
    public static final int hash = 1703748202;
    public int hash() {
        return tailfNcsAlarms.hash;
    }

    public static final String id = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/ncs-alarms";
    public String id() {
        return tailfNcsAlarms.id;
    }

    public static final String uri = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/ncs-alarms";
    public String uri() {
        return tailfNcsAlarms.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsAlarms.uri);
    }

    public static final String prefix = "al";
    public String prefix() {
        return tailfNcsAlarms.prefix;
    }

    public tailfNcsAlarms() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _alt_managed_object = 303095070;
    public static final String _alt_managed_object_ = "alt-managed-object";
    public static final int    _bad_user_input = 270356540;
    public static final String _bad_user_input_ = "bad-user-input";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _notify_cli = 1137138763;
    public static final String _notify_cli_ = "notify-cli";
    public static final int    _probable_cause = 1241890965;
    public static final String _probable_cause_ = "probable-cause";
    public static final int    _compress = 1232234516;
    public static final String _compress_ = "compress";
    public static final int    _last_changed = 125667375;
    public static final String _last_changed_ = "last-changed";
    public static final int    _majors = 2109263845;
    public static final String _majors_ = "majors";
    public static final int    _older_than = 1805080387;
    public static final String _older_than_ = "older-than";
    public static final int    _alarm_handling = 2140708342;
    public static final String _alarm_handling_ = "alarm-handling";
    public static final int    _compress_alarms = 1832830488;
    public static final String _compress_alarms_ = "compress-alarms";
    public static final int    _connection_failure = 603012695;
    public static final String _connection_failure_ = "connection-failure";
    public static final int    _user = 1529217067;
    public static final String _user_ = "user";
    public static final int    _impacted_objects = 1878758883;
    public static final String _impacted_objects_ = "impacted-objects";
    public static final int    _compressed_elements = 1272902988;
    public static final String _compressed_elements_ = "compressed-elements";
    public static final int    _sev_spec = 259977375;
    public static final String _sev_spec_ = "sev-spec";
    public static final int    _time = 190171445;
    public static final String _time_ = "time";
    public static final int    _cluster_subscriber_failure = 1830555976;
    public static final String _cluster_subscriber_failure_ = "cluster-subscriber-failure";
    public static final int    _event_time = 1896809242;
    public static final String _event_time_ = "event-time";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _new_alarms = 2096233586;
    public static final String _new_alarms_ = "new-alarms";
    public static final int    _alarm_class = 752923374;
    public static final String _alarm_class_ = "alarm-class";
    public static final int    _alarm_notification = 1458797552;
    public static final String _alarm_notification_ = "alarm-notification";
    public static final int    _missing_transaction_id = 382767440;
    public static final String _missing_transaction_id_ = "missing-transaction-id";
    public static final int    _is_cleared = 602088017;
    public static final String _is_cleared_ = "is-cleared";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _alarm_type = 1671421893;
    public static final String _alarm_type_ = "alarm-type";
    public static final int    _managed_object = 790683943;
    public static final String _managed_object_ = "managed-object";
    public static final int    _specific_problem = 1100390488;
    public static final String _specific_problem_ = "specific-problem";
    public static final int    _last_alarm_text = 1007243782;
    public static final String _last_alarm_text_ = "last-alarm-text";
    public static final int    _alarms = 1907669299;
    public static final String _alarms_ = "alarms";
    public static final int    _below = 22416181;
    public static final String _below_ = "below";
    public static final int    _purged_alarms = 840674541;
    public static final String _purged_alarms_ = "purged-alarms";
    public static final int    _number_of_alarms = 1505456559;
    public static final String _number_of_alarms_ = "number-of-alarms";
    public static final int    _package_operation_failure = 366060096;
    public static final String _package_operation_failure_ = "package-operation-failure";
    public static final int    _perceived_severity = 1194414666;
    public static final String _perceived_severity_ = "perceived-severity";
    public static final int    _received_time = 1032998934;
    public static final String _received_time_ = "received-time";
    public static final int    _related_alarms = 501485175;
    public static final String _related_alarms_ = "related-alarms";
    public static final int    _alarm = 1438310312;
    public static final String _alarm_ = "alarm";
    public static final int    _alarm_handling_state_filter = 2081327363;
    public static final String _alarm_handling_state_filter_ = "alarm-handling-state-filter";
    public static final int    _ncs_dev_manager_alarm = 1444042969;
    public static final String _ncs_dev_manager_alarm_ = "ncs-dev-manager-alarm";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _ha_alarm = 984351154;
    public static final String _ha_alarm_ = "ha-alarm";
    public static final int    _indeterminates = 1388563689;
    public static final String _indeterminates_ = "indeterminates";
    public static final int    _specific_problem_match = 1539295192;
    public static final String _specific_problem_match_ = "specific-problem-match";
    public static final int    _is = 1464808897;
    public static final String _is_ = "is";
    public static final int    _revision_error = 1855353530;
    public static final String _revision_error_ = "revision-error";
    public static final int    _above = 148921322;
    public static final String _above_ = "above";
    public static final int    _receiver_configuration_error = 1781702964;
    public static final String _receiver_configuration_error_ = "receiver-configuration-error";
    public static final int    _package_load_failure = 18987095;
    public static final String _package_load_failure_ = "package-load-failure";
    public static final int    _out_of_sync = 1890060877;
    public static final String _out_of_sync_ = "out-of-sync";
    public static final int    _notify_about_status_changes = 1910709920;
    public static final String _notify_about_status_changes_ = "notify-about-status-changes";
    public static final int    _filtered_key = 525239533;
    public static final String _filtered_key_ = "filtered-key";
    public static final int    _criticals = 2111388861;
    public static final String _criticals_ = "criticals";
    public static final int    _ncs_service_manager_alarm = 641815841;
    public static final String _ncs_service_manager_alarm_ = "ncs-service-manager-alarm";
    public static final int    _alarm_text = 1518107580;
    public static final String _alarm_text_ = "alarm-text";
    public static final int    _ha_master_down = 1042266698;
    public static final String _ha_master_down_ = "ha-master-down";
    public static final int    _commit_through_queue_blocked = 1139641471;
    public static final String _commit_through_queue_blocked_ = "commit-through-queue-blocked";
    public static final int    _hours = 1625129637;
    public static final String _hours_ = "hours";
    public static final int    _filter_level = 252231578;
    public static final String _filter_level_ = "filter-level";
    public static final int    _last_status_change = 1438934416;
    public static final String _last_status_change_ = "last-status-change";
    public static final int    _ncs_package_alarm = 296151549;
    public static final String _ncs_package_alarm_ = "ncs-package-alarm";
    public static final int    _root_cause_objects = 186100657;
    public static final String _root_cause_objects_ = "root-cause-objects";
    public static final int    _configuration_error = 599021844;
    public static final String _configuration_error_ = "configuration-error";
    public static final int    _max_status_change_entries_per_alarm = 1262264437;
    public static final String _max_status_change_entries_per_alarm_ = "max-status-change-entries-per-alarm";
    public static final int    _minutes = 1222309332;
    public static final String _minutes_ = "minutes";
    public static final int    _ha_node_down_alarm = 1312543818;
    public static final String _ha_node_down_alarm_ = "ha-node-down-alarm";
    public static final int    _has_clear = 1773853621;
    public static final String _has_clear_ = "has-clear";
    public static final int    _alarm_model = 416401090;
    public static final String _alarm_model_ = "alarm-model";
    public static final int    _ha_slave_down = 1944418976;
    public static final String _ha_slave_down_ = "ha-slave-down";
    public static final int    _commit_through_queue_failed = 268737458;
    public static final String _commit_through_queue_failed_ = "commit-through-queue-failed";
    public static final int    _last_perceived_severity = 1196634400;
    public static final String _last_perceived_severity_ = "last-perceived-severity";
    public static final int    _final_commit_error = 267824093;
    public static final String _final_commit_error_ = "final-commit-error";
    public static final int    _handle_alarm = 69635206;
    public static final String _handle_alarm_ = "handle-alarm";
    public static final int    _synchronize_alarms = 1554702790;
    public static final String _synchronize_alarms_ = "synchronize-alarms";
    public static final int    _control = 573205060;
    public static final String _control_ = "control";
    public static final int    _event_type = 1079952141;
    public static final String _event_type_ = "event-type";
    public static final int    _days = 723976734;
    public static final String _days_ = "days";
    public static final int    _weeks = 323453812;
    public static final String _weeks_ = "weeks";
    public static final int    _minors = 151115970;
    public static final String _minors_ = "minors";
    public static final int    _ncs_snmp_notification_receiver_alarm = 1728411776;
    public static final String _ncs_snmp_notification_receiver_alarm_ = "ncs-snmp-notification-receiver-alarm";
    public static final int    _purge = 521476653;
    public static final String _purge_ = "purge";
    public static final int    _last_alarm_handling_change = 596328014;
    public static final String _last_alarm_handling_change_ = "last-alarm-handling-change";
    public static final int    _status_change = 1027325453;
    public static final String _status_change_ = "status-change";
    public static final int    _kind_of_alarm = 824564444;
    public static final String _kind_of_alarm_ = "kind-of-alarm";
    public static final int    _service_activation_failure = 1634227461;
    public static final String _service_activation_failure_ = "service-activation-failure";
    public static final int    _abort_error = 1036333841;
    public static final String _abort_error_ = "abort-error";
    public static final int    _purge_alarms = 1352333389;
    public static final String _purge_alarms_ = "purge-alarms";
    public static final int    _alarm_list = 1725305220;
    public static final String _alarm_list_ = "alarm-list";
    public static final int    _commit_through_queue_rollback_failed = 1099029044;
    public static final String _commit_through_queue_rollback_failed_ = "commit-through-queue-rollback-failed";
    public static final int    _cleared_alarms = 568653883;
    public static final String _cleared_alarms_ = "cleared-alarms";
    public static final int    _changed_alarms = 2145124414;
    public static final String _changed_alarms_ = "changed-alarms";
    public static final int    _severity = 483607279;
    public static final String _severity_ = "severity";
    public static final int    _warnings = 1313110827;
    public static final String _warnings_ = "warnings";
    public static final int    _alarm_status = 1979041785;
    public static final String _alarm_status_ = "alarm-status";
    public static final int    _age_spec = 1564313084;
    public static final String _age_spec_ = "age-spec";
    public static final int    _filter_alarms = 1348252258;
    public static final String _filter_alarms_ = "filter-alarms";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _ned_live_tree_connection_failure = 735529133;
    public static final String _ned_live_tree_connection_failure_ = "ned-live-tree-connection-failure";
    public static final int    _ncs_cluster_alarm = 853839633;
    public static final String _ncs_cluster_alarm_ = "ncs-cluster-alarm";
    public static final int    _seconds = 1442107370;
    public static final String _seconds_ = "seconds";
    public static final int    _alarm_summary = 894916599;
    public static final String _alarm_summary_ = "alarm-summary";
}
