/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.6.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.6.yang */
public class tailfNedIdCiscoNsoNc5_6 extends ConfNamespace {
    public static final int hash = 1276823297;
    public int hash() {
        return tailfNedIdCiscoNsoNc5_6.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.6";
    public String id() {
        return tailfNedIdCiscoNsoNc5_6.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.6";
    public String uri() {
        return tailfNedIdCiscoNsoNc5_6.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNsoNc5_6.uri);
    }

    public static final String prefix = "cisco-nso-nc-5.6";
    public String prefix() {
        return tailfNedIdCiscoNsoNc5_6.prefix;
    }

    public tailfNedIdCiscoNsoNc5_6() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nso_nc_50x2e6 = 2027256942;
    public static final String _cisco_nso_nc_50x2e6_ = "cisco-nso-nc-5.6";
}
