/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-kicker.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-kicker.yang */
public class tailfKicker extends ConfNamespace {
    public static final int hash = 1856946935;
    public int hash() {
        return tailfKicker.hash;
    }

    public static final String id = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/kicker";
    public String id() {
        return tailfKicker.id;
    }

    public static final String uri = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/kicker";
    public String uri() {
        return tailfKicker.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfKicker.uri);
    }

    public static final String prefix = "kicker";
    public String prefix() {
        return tailfKicker.prefix;
    }

    public tailfKicker() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _send_kicker_triggered = 2072134941;
    public static final String _send_kicker_triggered_ = "send-kicker-triggered";
    public static final int    _config_false = 2031849564;
    public static final String _config_false_ = "config-false";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _trigger_type = 1997820812;
    public static final String _trigger_type_ = "trigger-type";
    public static final int    _action_name = 719374744;
    public static final String _action_name_ = "action-name";
    public static final int    _exclude = 1901477268;
    public static final String _exclude_ = "exclude";
    public static final int    _trigger_expr = 1295597193;
    public static final String _trigger_expr_ = "trigger-expr";
    public static final int    _kick_node = 1324530621;
    public static final String _kick_node_ = "kick-node";
    public static final int    _kicker_id = 1615011589;
    public static final String _kicker_id_ = "kicker-id";
    public static final int    _tid = 805616318;
    public static final String _tid_ = "tid";
    public static final int    _filter = 518848087;
    public static final String _filter_ = "filter";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _kickers = 1612823674;
    public static final String _kickers_ = "kickers";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _config_true = 1801250214;
    public static final String _config_true_ = "config-true";
    public static final int    _variable = 488361488;
    public static final String _variable_ = "variable";
    public static final int    _data_kicker = 1888429244;
    public static final String _data_kicker_ = "data-kicker";
    public static final int    _kicker_triggered = 1569812249;
    public static final String _kicker_triggered_ = "kicker-triggered";
    public static final int    _monitor = 617812454;
    public static final String _monitor_ = "monitor";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _serializer = 1394029981;
    public static final String _serializer_ = "serializer";
}
