#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.5.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.5.yang


class ns(object):
    hash = 1412712676

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.5"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.5"

    prefix = "cisco-nso-nc-5.5"

    cisco_nso_nc_50x2e5_cisco_nso_nc_50x2e5 = 1021010265
    cisco_nso_nc_50x2e5_cisco_nso_nc_50x2e5_ = "cisco-nso-nc-5.5"
