#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-yang-library.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-yang-library.yang


class ns(object):
    hash = 2095755791

    id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#urn:ietf:params:xml:ns:yang:ietf-yang-library"

    uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#urn:ietf:params:xml:ns:yang:ietf-yang-library"

    prefix = "yanglib"

    yanglib_yang_library_update = 370442749
    yanglib_yang_library_update_ = "yang-library-update"
    yanglib_implement = 0
    yanglib_implement_ = "implement"
    yanglib_location = 1827424758
    yanglib_location_ = "location"
    yanglib_schema = 1919828639
    yanglib_schema_ = "schema"
    yanglib_module_set = 1717791695
    yanglib_module_set_ = "module-set"
    yanglib_revision = 1794066410
    yanglib_revision_ = "revision"
    yanglib_import_only_module = 1755824327
    yanglib_import_only_module_ = "import-only-module"
    yanglib_datastore = 449538578
    yanglib_datastore_ = "datastore"
    yanglib_feature = 2072953574
    yanglib_feature_ = "feature"
    yanglib_yang_library_change = 385569445
    yanglib_yang_library_change_ = "yang-library-change"
    yanglib_deviation = 1796840446
    yanglib_deviation_ = "deviation"
    yanglib_modules_state = 1352300643
    yanglib_modules_state_ = "modules-state"
    yanglib_content_id = 88837684
    yanglib_content_id_ = "content-id"
    yanglib_namespace = 1847615892
    yanglib_namespace_ = "namespace"
    yanglib_yang_library = 1402909805
    yanglib_yang_library_ = "yang-library"
    yanglib_conformance_type = 1162662605
    yanglib_conformance_type_ = "conformance-type"
    yanglib_name = 1998270519
    yanglib_name_ = "name"
    yanglib_module_set_id = 1560116046
    yanglib_module_set_id_ = "module-set-id"
    yanglib_import = 1
    yanglib_import_ = "import"
    yanglib_module = 241869139
    yanglib_module_ = "module"
    yanglib_submodule = 1477119504
    yanglib_submodule_ = "submodule"
