#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-ned.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-ned.yang


class ns(object):
    hash = 70095624

    id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/ncs-ned"

    uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/ncs-ned"

    prefix = "ned"

    ned_netconf_ned_id = 973516117
    ned_netconf_ned_id_ = "netconf-ned-id"
    ned_rfc5277_id = 37234262
    ned_rfc5277_id_ = "rfc5277-id"
    ned_cli_ned_id = 868449949
    ned_cli_ned_id_ = "cli-ned-id"
    ned_snmp = 1480446066
    ned_snmp_ = "snmp"
    ned_netconf = 1625535416
    ned_netconf_ = "netconf"
    ned_ned_id = 1774190712
    ned_ned_id_ = "ned-id"
    ned_generic_ned_id = 878713830
    ned_generic_ned_id_ = "generic-ned-id"
    ned_lsa_netconf = 1104954683
    ned_lsa_netconf_ = "lsa-netconf"
    ned_snmp_ned_id = 1834620094
    ned_snmp_ned_id_ = "snmp-ned-id"
