#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-acm.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-acm.yang


class ns(object):
    hash = 1853056478

    id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/yang/ncs-acm"

    uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/yang/ncs-acm"

    prefix = "tnacm"

    tnacm_enforce_nacm_on_services = 646091520
    tnacm_enforce_nacm_on_services_ = "enforce-nacm-on-services"
