#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-kicker.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-kicker.yang


class ns(object):
    hash = 1943231063

    id = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/kicker"

    uri = "_cisco-nso-nc-5.5:cisco-nso-nc-5.5#http://tail-f.com/ns/kicker"

    prefix = "kicker"

    kicker_path = 1002915403
    kicker_path_ = "path"
    kicker_send_kicker_triggered = 2072134941
    kicker_send_kicker_triggered_ = "send-kicker-triggered"
    kicker_config_false = 2031849564
    kicker_config_false_ = "config-false"
    kicker_enter_and_leave = 0
    kicker_enter_and_leave_ = "enter-and-leave"
    kicker_value = 864367181
    kicker_value_ = "value"
    kicker_trigger_type = 1997820812
    kicker_trigger_type_ = "trigger-type"
    kicker_action_name = 719374744
    kicker_action_name_ = "action-name"
    kicker_exclude = 1901477268
    kicker_exclude_ = "exclude"
    kicker_trigger_expr = 1295597193
    kicker_trigger_expr_ = "trigger-expr"
    kicker_kick_node = 1324530621
    kicker_kick_node_ = "kick-node"
    kicker_kicker_id = 1615011589
    kicker_kicker_id_ = "kicker-id"
    kicker_tid = 805616318
    kicker_tid_ = "tid"
    kicker_filter = 518848087
    kicker_filter_ = "filter"
    kicker_priority = 1346277862
    kicker_priority_ = "priority"
    kicker_config = 2105663071
    kicker_config_ = "config"
    kicker_kickers = 1612823674
    kicker_kickers_ = "kickers"
    kicker_name = 1998270519
    kicker_name_ = "name"
    kicker_config_true = 1801250214
    kicker_config_true_ = "config-true"
    kicker_variable = 488361488
    kicker_variable_ = "variable"
    kicker_enter = 1
    kicker_enter_ = "enter"
    kicker_data_kicker = 1888429244
    kicker_data_kicker_ = "data-kicker"
    kicker_kicker_triggered = 1569812249
    kicker_kicker_triggered_ = "kicker-triggered"
    kicker_monitor = 617812454
    kicker_monitor_ = "monitor"
    kicker_id = 1279252765
    kicker_id_ = "id"
    kicker_serializer = 1394029981
    kicker_serializer_ = "serializer"
