#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.6.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.6.yang


class ns(object):
    hash = 1276823297

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.6"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.6"

    prefix = "cisco-nso-nc-5.6"

    cisco_nso_nc_50x2e6_cisco_nso_nc_50x2e6 = 2027256942
    cisco_nso_nc_50x2e6_cisco_nso_nc_50x2e6_ = "cisco-nso-nc-5.6"
