#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-netconf-acm.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-netconf-acm.yang


class ns(object):
    hash = 1157769520

    id = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#urn:ietf:params:xml:ns:yang:ietf-netconf-acm"

    uri = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#urn:ietf:params:xml:ns:yang:ietf-netconf-acm"

    prefix = "nacm"

    nacm__bm_live_ncs_access_operations_type_update = 4
    nacm__bm_live_ncs_access_operations_type_update_ = "update"
    nacm_path = 1002915403
    nacm_path_ = "path"
    nacm_access_operations = 1622834780
    nacm_access_operations_ = "access-operations"
    nacm_rule = 661146188
    nacm_rule_ = "rule"
    nacm_permit = 0
    nacm_permit_ = "permit"
    nacm__bm_live_ncs_access_operations_type_read = 2
    nacm__bm_live_ncs_access_operations_type_read_ = "read"
    nacm__bm_ncs_rpc_notif_access_operations_type_create = 1
    nacm__bm_ncs_rpc_notif_access_operations_type_create_ = "create"
    nacm_read_default = 1809256375
    nacm_read_default_ = "read-default"
    nacm__bm_live_ncs_access_operations_type_delete = 8
    nacm__bm_live_ncs_access_operations_type_delete_ = "delete"
    nacm_protocol_operation = 1730844454
    nacm_protocol_operation_ = "protocol-operation"
    nacm_module_name = 1521916861
    nacm_module_name_ = "module-name"
    nacm_enable_external_groups = 681474854
    nacm_enable_external_groups_ = "enable-external-groups"
    nacm__bm_access_operations_type_read = 2
    nacm__bm_access_operations_type_read_ = "read"
    nacm_denied_notifications = 1423413556
    nacm_denied_notifications_ = "denied-notifications"
    nacm__bm_ncs_rpc_notif_access_operations_type_exec = 16
    nacm__bm_ncs_rpc_notif_access_operations_type_exec_ = "exec"
    nacm__bm_live_ncs_access_operations_type_create = 1
    nacm__bm_live_ncs_access_operations_type_create_ = "create"
    nacm__bm_access_operations_type_update = 4
    nacm__bm_access_operations_type_update_ = "update"
    nacm_nacm = 882296017
    nacm_nacm_ = "nacm"
    nacm_groups = 575296803
    nacm_groups_ = "groups"
    nacm__bm_ncs_rpc_notif_access_operations_type_read = 2
    nacm__bm_ncs_rpc_notif_access_operations_type_read_ = "read"
    nacm_notification = 232240424
    nacm_notification_ = "notification"
    nacm__bm_live_ncs_access_operations_type_exec = 16
    nacm__bm_live_ncs_access_operations_type_exec_ = "exec"
    nacm_data_node = 1323346008
    nacm_data_node_ = "data-node"
    nacm_group = 1540685982
    nacm_group_ = "group"
    nacm_write_default = 342649280
    nacm_write_default_ = "write-default"
    nacm__bm_ncs_rpc_notif_access_operations_type_delete = 8
    nacm__bm_ncs_rpc_notif_access_operations_type_delete_ = "delete"
    nacm__bm_access_operations_type_exec = 16
    nacm__bm_access_operations_type_exec_ = "exec"
    nacm_exec_default = 1365079393
    nacm_exec_default_ = "exec-default"
    nacm_notification_name = 1826218130
    nacm_notification_name_ = "notification-name"
    nacm__bm_access_operations_type_create = 1
    nacm__bm_access_operations_type_create_ = "create"
    nacm_denied_data_writes = 1067903842
    nacm_denied_data_writes_ = "denied-data-writes"
    nacm_denied_operations = 1711027331
    nacm_denied_operations_ = "denied-operations"
    nacm_rule_list = 755335822
    nacm_rule_list_ = "rule-list"
    nacm_user_name = 1672949661
    nacm_user_name_ = "user-name"
    nacm_comment = 452863039
    nacm_comment_ = "comment"
    nacm__bm_ncs_rpc_notif_access_operations_type_update = 4
    nacm__bm_ncs_rpc_notif_access_operations_type_update_ = "update"
    nacm_name = 1998270519
    nacm_name_ = "name"
    nacm_rule_type = 508857660
    nacm_rule_type_ = "rule-type"
    nacm__bm_access_operations_type_delete = 8
    nacm__bm_access_operations_type_delete_ = "delete"
    nacm_enable_nacm = 947489807
    nacm_enable_nacm_ = "enable-nacm"
    nacm_deny = 1
    nacm_deny_ = "deny"
    nacm_rpc_name = 37201271
    nacm_rpc_name_ = "rpc-name"
    nacm_action = 571883887
    nacm_action_ = "action"
