#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-kicker-extension.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-kicker-extension.yang


class ns(object):
    hash = 1901140557

    id = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/ncs-kicker"

    uri = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/ncs-kicker"

    prefix = "ncs-kicker"

    ncs_kicker_value = 864367181
    ncs_kicker_value_ = "value"
    ncs_kicker_action_name = 719374744
    ncs_kicker_action_name_ = "action-name"
    ncs_kicker_kick_node = 1324530621
    ncs_kicker_kick_node_ = "kick-node"
    ncs_kicker_priority = 1346277862
    ncs_kicker_priority_ = "priority"
    ncs_kicker_name = 1998270519
    ncs_kicker_name_ = "name"
    ncs_kicker_variable = 488361488
    ncs_kicker_variable_ = "variable"
    ncs_kicker_selector_expr = 764630658
    ncs_kicker_selector_expr_ = "selector-expr"
    ncs_kicker_notification_kicker = 1296828952
    ncs_kicker_notification_kicker_ = "notification-kicker"
    ncs_kicker_id = 1279252765
    ncs_kicker_id_ = "id"
