#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-common-monitoring.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-common-monitoring.yang


class ns(object):
    hash = 1770278492

    id = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/yang/common-monitoring"

    uri = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/yang/common-monitoring"

    prefix = "tfcg"

    tfcg_subscription = 1
    tfcg_subscription_ = "subscription"
    tfcg_pending_subscription = 3
    tfcg_pending_subscription_ = "pending-subscription"
    tfcg_waiting = 3
    tfcg_waiting_ = "waiting"
    tfcg_phase0 = 1
    tfcg_phase0_ = "phase0"
    tfcg_subscriber = 2
    tfcg_subscriber_ = "subscriber"
    tfcg_slave = 1
    tfcg_slave_ = "slave"
    tfcg_none = 0
    tfcg_none_ = "none"
    tfcg_pending_read = 2
    tfcg_pending_read_ = "pending-read"
    tfcg_phase1 = 2
    tfcg_phase1_ = "phase1"
    tfcg_master = 2
    tfcg_master_ = "master"
    tfcg_starting = 0
    tfcg_starting_ = "starting"
    tfcg_external = 2
    tfcg_external_ = "external"
    tfcg_inactive = 0
    tfcg_inactive_ = "inactive"
    tfcg_PENDING = 0
    tfcg_PENDING_ = "PENDING"
    tfcg_UNKNOWN = 1
    tfcg_UNKNOWN_ = "UNKNOWN"
    tfcg_read = 0
    tfcg_read_ = "read"
    tfcg_NOT_REGISTERED = 0
    tfcg_NOT_REGISTERED_ = "NOT-REGISTERED"
    tfcg_stopping = 4
    tfcg_stopping_ = "stopping"
    tfcg_builtin = 1
    tfcg_builtin_ = "builtin"
    tfcg_started = 3
    tfcg_started_ = "started"
    tfcg_relay_slave = 3
    tfcg_relay_slave_ = "relay-slave"
    tfcg_client = 1
    tfcg_client_ = "client"
