#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-netconf-ned-builder.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-netconf-ned-builder.yang


class ns(object):
    hash = 218345121

    id = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/ncs/netconf-ned-builder"

    uri = "_cisco-nso-nc-5.6:cisco-nso-nc-5.6#http://tail-f.com/ns/ncs/netconf-ned-builder"

    prefix = "tnnb"

    tnnb_bit_dl_error = 32
    tnnb_bit_dl_error_ = "download-error"
    tnnb_bit_deselected = 1
    tnnb_bit_deselected_ = "deselected"
    tnnb_profile = 1538168517
    tnnb_profile_ = "profile"
    tnnb_compiler_output = 1578604919
    tnnb_compiler_output_ = "compiler-output"
    tnnb_location = 1827424758
    tnnb_location_ = "location"
    tnnb_ned_directory_path = 1576761495
    tnnb_ned_directory_path_ = "ned-directory-path"
    tnnb_max_download_threads = 31300361
    tnnb_max_download_threads_ = "max-download-threads"
    tnnb_error = 1
    tnnb_error_ = "error"
    tnnb_build_ned = 36493425
    tnnb_build_ned_ = "build-ned"
    tnnb_build_status = 278800061
    tnnb_build_status_ = "build-status"
    tnnb_build_error = 1281833628
    tnnb_build_error_ = "build-error"
    tnnb_selected = 1500137012
    tnnb_selected_ = "selected"
    tnnb_result = 401396173
    tnnb_result_ = "result"
    tnnb_not_found = 1919731247
    tnnb_not_found_ = "not-found"
    tnnb_device = 617911018
    tnnb_device_ = "device"
    tnnb_applied = 0
    tnnb_applied_ = "applied"
    tnnb_status = 1950810920
    tnnb_status_ = "status"
    tnnb_bit_pending = 8
    tnnb_bit_pending_ = "pending"
    tnnb_save_selection = 2116845479
    tnnb_save_selection_ = "save-selection"
    tnnb_revision = 1794066410
    tnnb_revision_ = "revision"
    tnnb_select_info = 1110820427
    tnnb_select_info_ = "select-info"
    tnnb_no_dependencies = 390660413
    tnnb_no_dependencies_ = "no-dependencies"
    tnnb_build_warning = 504037989
    tnnb_build_warning_ = "build-warning"
    tnnb_ned_path = 1667349253
    tnnb_ned_path_ = "ned-path"
    tnnb_no_revisions = 805099600
    tnnb_no_revisions_ = "no-revisions"
    tnnb_to_directory = 134604797
    tnnb_to_directory_ = "to-directory"
    tnnb_feature = 2072953574
    tnnb_feature_ = "feature"
    tnnb_make_development_ned = 1064213877
    tnnb_make_development_ned_ = "make-development-ned"
    tnnb_deviation = 1796840446
    tnnb_deviation_ = "deviation"
    tnnb_ambiguous = 390658914
    tnnb_ambiguous_ = "ambiguous"
    tnnb_fetch_module_list = 26030237
    tnnb_fetch_module_list_ = "fetch-module-list"
    tnnb_vendor = 1639541835
    tnnb_vendor_ = "vendor"
    tnnb_build_error_info = 1867763619
    tnnb_build_error_info_ = "build-error-info"
    tnnb_bit_no_deps = 4
    tnnb_bit_no_deps_ = "no-dependencies"
    tnnb_local_user = 1479564322
    tnnb_local_user_ = "local-user"
    tnnb_in_directory = 1836397949
    tnnb_in_directory_ = "in-directory"
    tnnb_bit_selected = 2
    tnnb_bit_selected_ = "selected"
    tnnb_namespace = 1847615892
    tnnb_namespace_ = "namespace"
    tnnb_NETCONF = 0
    tnnb_NETCONF_ = "NETCONF"
    tnnb_best_effort = 1556684121
    tnnb_best_effort_ = "best-effort"
    tnnb_deselect = 1534284528
    tnnb_deselect_ = "deselect"
    tnnb_name = 1998270519
    tnnb_name_ = "name"
    tnnb_select = 1473597411
    tnnb_select_ = "select"
    tnnb_netconf_ned_builder = 1727329174
    tnnb_netconf_ned_builder_ = "netconf-ned-builder"
    tnnb_project = 934555478
    tnnb_project_ = "project"
    tnnb_download_cache_path = 1831947648
    tnnb_download_cache_path_ = "download-cache-path"
    tnnb_apply = 1468797760
    tnnb_apply_ = "apply"
    tnnb_major_version = 423255377
    tnnb_major_version_ = "major-version"
    tnnb_export_ned = 226564769
    tnnb_export_ned_ = "export-ned"
    tnnb_import = 82100561
    tnnb_import_ = "import"
    tnnb_bit_downloaded = 16
    tnnb_bit_downloaded_ = "downloaded"
    tnnb_tar_file = 1643132563
    tnnb_tar_file_ = "tar-file"
    tnnb_success = 0
    tnnb_success_ = "success"
    tnnb_family_name = 1394315061
    tnnb_family_name_ = "family-name"
    tnnb_not_applied = 1
    tnnb_not_applied_ = "not-applied"
    tnnb_module = 241869139
    tnnb_module_ = "module"
    tnnb_with_dependencies = 176147827
    tnnb_with_dependencies_ = "with-dependencies"
    tnnb_overwrite = 1560339033
    tnnb_overwrite_ = "overwrite"
    tnnb_submodule = 1477119504
    tnnb_submodule_ = "submodule"
    actionpoint_dir_path_comp = "dir-path-comp"
