/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-cisco-ios-xr-meta.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-xr-meta.yang */
public class CiscoIosXrMeta extends ConfNamespace {
    public static final int hash = 726576819;
    public int hash() {
        return CiscoIosXrMeta.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-iosxr/meta";
    public String id() {
        return CiscoIosXrMeta.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-iosxr/meta";
    public String uri() {
        return CiscoIosXrMeta.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIosXrMeta.uri);
    }

    public static final String prefix = "cisco-ios-xr-meta";
    public String prefix() {
        return CiscoIosXrMeta.prefix;
    }

    public CiscoIosXrMeta() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_iosxr_transaction_id_method = 755244827;
    public static final String _cisco_iosxr_transaction_id_method_ = "cisco-iosxr-transaction-id-method";
}
