/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-xr-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-xr-stats.yang */
public class CiscoIosXrStats extends ConfNamespace {
    public static final int hash = 261001257;
    public int hash() {
        return CiscoIosXrStats.hash;
    }

    public static final String id = "_cisco-iosxr-cli-3.5:cisco-iosxr-cli-3.5#http://tail-f.com/ned/cisco-ios-xr-stats";
    public String id() {
        return CiscoIosXrStats.id;
    }

    public static final String uri = "_cisco-iosxr-cli-3.5:cisco-iosxr-cli-3.5#http://tail-f.com/ned/cisco-ios-xr-stats";
    public String uri() {
        return CiscoIosXrStats.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIosXrStats.uri);
    }

    public static final String prefix = "cisco-ios-xr-stats";
    public String prefix() {
        return CiscoIosXrStats.prefix;
    }

    public CiscoIosXrStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ping = 888696325;
    public static final String _ping_ = "ping";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _exec = 1716494663;
    public static final String _exec_ = "exec";
    public static final int    _crypto = 1089763547;
    public static final String _crypto_ = "crypto";
    public static final int    _traceroute = 739383050;
    public static final String _traceroute_ = "traceroute";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _clear = 634788371;
    public static final String _clear_ = "clear";
    public static final int    _args = 578380655;
    public static final String _args_ = "args";
    public static final int    _reload = 1336127569;
    public static final String _reload_ = "reload";
    public static final int    _copy = 1887233912;
    public static final String _copy_ = "copy";
    public static final int    _show = 1568086057;
    public static final String _show_ = "show";
}
