/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-iosxr-cli-3.5.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-iosxr-cli-3.5.yang */
public class tailfCiscoIosxrId extends ConfNamespace {
    public static final int hash = 683382498;
    public int hash() {
        return tailfCiscoIosxrId.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-iosxr-cli-3.5";
    public String id() {
        return tailfCiscoIosxrId.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-iosxr-cli-3.5";
    public String uri() {
        return tailfCiscoIosxrId.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfCiscoIosxrId.uri);
    }

    public static final String prefix = "cisco-iosxr-cli-3.5";
    public String prefix() {
        return tailfCiscoIosxrId.prefix;
    }

    public tailfCiscoIosxrId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_iosxr_cli_30x2e5 = 869204534;
    public static final String _cisco_iosxr_cli_30x2e5_ = "cisco-iosxr-cli-3.5";
}
