#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.7.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.7.yang


class ns(object):
    hash = 524657401

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.7"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.7"

    prefix = "cisco-nso-nc-5.7"

    cisco_nso_nc_50x2e7_cisco_nso_nc_50x2e7 = 1772392966
    cisco_nso_nc_50x2e7_cisco_nso_nc_50x2e7_ = "cisco-nso-nc-5.7"
